services:
  - type: web
    name: police-case-analysis
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: police-case-db
          property: connectionString

databases:
  - name: police-case-db
    plan: free
    databaseName: police_case_analysis
    user: police_user
